'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const deals = require('../modules/deals/reviewed-deals');
const imports = require('../modules/buyers/buyer-find-import');
const { fixture, buyer, now } = require('./reviewed-deals.test');
const context = { now, operatorId:'fixture-operator', createId:()=> 'fixture-deal' };
const original = deals.ingest({buyers:[buyer],leads:[{id:'untouched'}]},[deals.validate({...fixture(),ref:'WOS-FL-1012'},now)],context).store;
const approved = deals.update(original,'fixture-deal',{action:'approve',reviewed_comps:true},context);
const deal = approved.reviewed_deals[0];
const ranged = {...buyer,record_ref:'BUY-0005',assistant_find:{...buyer.assistant_find,buy_box:{types:['house'],pct_arv:'60-70%',exclusions:['major structural'],construction:'block preferred',flood:'X',rehab_tolerance:'cosmetic'}}};
let evaluation = deals.evaluate(deal,[ranged],now);
assert.equal(evaluation.matches[0].buyer_ref,'BUY-0005');
assert.equal(evaluation.matches[0].max_price,130600);
assert.ok(evaluation.matches[0].reasons.includes('60-70% of ARV (low end used)'));
assert.ok(evaluation.matches[0].check_items.some(c=>c.includes('major structural')));
assert.equal(deals.evaluate({...deal,flood_zone:'AE'},[ranged],now).matches.length,0);
assert.equal(deals.evaluate({...deal,flood_zone:'X'},[ranged],now).matches.length,1);
const pending = deals.evaluate(original.reviewed_deals[0],[ranged],now);
assert.equal(pending.matches.length,1);assert.equal(pending.matches[0].max_price,null);
assert.equal(pending.matches[0].estimated_spread,null);assert.equal(pending.jv_eligible,false);assert.equal(pending.introduction_allowed,false);
assert.notEqual(pending.ready_to_offer,'YES');
for(const pct of ['70-60%','0-70%','60-100%','60% plus conditions']) assert.equal(deals.evaluate(deal,[{...ranged,assistant_find:{...ranged.assistant_find,buy_box:{pct_arv:pct}}}],now).matches.length,0);
for(const patch of [{approval:'pending'}, {classification:'broker'}]) assert.equal(deals.evaluate(deal,[{...ranged,assistant_find:{...ranged.assistant_find,...patch}}],now).matches.length,0);
assert.equal(deals.evaluate({...deal,state:'NY'},[ranged],now).matches.length,0);
assert.equal(deals.evaluate({...deal,property_type:'land'},[ranged],now).matches.length,0);
const update = {kind:'deal_update',ref:'WOS-FL-1012',source_url:'https://records.example.test/holder-terms',captured_at:now,evidence_text:'Holder supplied a 25% fee split and closing details.',jv_split:0.25,closing_date:'October 25, 2026',title_company:'Fixture title company',latitude:27.95,longitude:-82.45};
const saved = JSON.stringify(approved);
const plan = imports.prepareImport(approved,{items:[update]},{now});
assert.equal(plan.summary.counts.updates,1);assert.equal(plan.summary.counts.new_items,0);
assert.equal(JSON.stringify(approved),saved);assert.ok(!JSON.stringify(plan.summary).includes(deal.address));
let result = imports.commitImport(approved,plan,{...context,bulkApprove:true});
assert.equal(result.summary.updated,1);assert.equal(result.store.reviewed_deals.length,1);
let revised = result.store.reviewed_deals[0];
assert.equal(revised.record_ref,'WOS-FL-1012');assert.equal(revised.jv_split,0.25);assert.equal(revised.approval,'approved');
assert.equal(revised.evidence_reviewed_at,deal.evidence_reviewed_at);assert.equal(revised.closing_date,'2026-10-25');
assert.equal(revised.status,deal.status);assert.deepEqual(result.store.leads,approved.leads);
assert.equal(result.store.activities.length,(approved.activities || []).length+1);
assert.ok(result.store.activities.at(-1).changes.some(c=>c.field==='jv_split'&&c.old_value===0.5&&c.new_value===0.25));
assert.equal(revised.field_provenance.jv_split.source_url,update.source_url);
assert.throws(()=>imports.commitImport({...approved,reviewed_deals:[{...deal,approval:'rejected'}]},plan,context),/update_conflict/);
const replay = imports.prepareImport(result.store,{items:[update]},{now});assert.equal(replay.summary.counts.duplicates,1);
const comps = revised.comps.map(c=>({...c,sold_price:c.sold_price+1000}));
const compPlan = imports.prepareImport(result.store,{items:[{...update,comps}]},{now});
result = imports.commitImport(result.store,compPlan,context);revised=result.store.reviewed_deals[0];
assert.equal(revised.approval,'pending');assert.equal(revised.evidence_reviewed_at,'');assert.equal(revised.evidence_reviewed_by,'');
assert.equal(deals.evaluate(revised,[ranged],now).value.tier,'Not established');
const stale = {...update,captured_at:'2026-10-06T12:00:00Z',jv_split:0.3};
assert.throws(()=>deals.ingest(result.store,[stale],context),/update_stale/);
for(const bad of [{...update,ref:'WOS-FL-9999'},{...update,status:'closed'},{...update,approval:'approved'},{...update,source_url:'http://records.example.test/'},{...update,captured_at:'2030-01-01T00:00:00Z'},{...update,evidence_text:''},{...update,jv_split:2},{...update,latitude:91},{...update,comps:[{...comps[0],comp_grid:{accepted:true}}]}]) assert.equal(imports.prepareImport(approved,{items:[bad]},{now}).summary.counts.rejected,1);
assert.throws(()=>deals.validateDealUpdate({...approved,reviewed_deals:[deal,{...deal,id:'duplicate-ref'}]},update,now),/reference_ambiguous/);
const terms = deals.update(approved,'fixture-deal',{action:'terms',jv_split:0.25,reason:'Holder stated 25% share.',evidence_url:update.source_url},context);
assert.equal(terms.reviewed_deals[0].jv_split,0.25);assert.equal(terms.reviewed_deals[0].approval,'approved');
assert.throws(()=>deals.update(approved,'fixture-deal',{action:'terms',jv_split:0.25},context),/terms_required/);
assert.throws(()=>deals.update(approved,'fixture-deal',{action:'approve',jv_split:0.25,reviewed_comps:true},context),/update_invalid/);
assert.throws(()=>deals.update(original,'fixture-deal',{action:'approve',reviewed_comps:false},context),/review_required/);
const restore={fetch:global.fetch,clock:Date.now,write:fs.writeFileSync};let calls=0;
try { const forbidden=()=>{calls++;throw Error('forbidden side effect');};global.fetch=forbidden;Date.now=forbidden;fs.writeFileSync=forbidden;deals.evaluate(deal,[ranged],now);imports.prepareImport(approved,{items:[update]},{now}); } finally {global.fetch=restore.fetch;Date.now=restore.clock;fs.writeFileSync=restore.write;}
assert.equal(calls,0);
console.log('Buyer ranges/checks, geographic candidates, conservative ceiling, update-by-ref audit, concurrency, review reset, unsafe/stale inputs and purity passed.');
