'use strict';
const assert = require('assert'); const fs = require('fs');
const records = require('../modules/records/record-activity');
const now = '2026-10-08T01:00:00Z'; const context = { now, operatorId: 'admin' };
const seed = { users: [{ id: 'admin', name: 'Fixture operator' }], leads: [{ id: 'lead1', state: 'FL', reference_id: 'LEGACY-1', address: 'Fixture source' }], buyers: [{ id: 'buyer1', name: 'Fixture buyer' }], reviewed_deals: [{ id: 'deal1', state: 'FL', address: 'Fixture deal' }], activities: [{ activity_id: 'old', lead_id: 'lead1', type: 'note', note: 'Historical note', created_at: '2026-10-01T12:00:00Z', created_by: 'operator' }] };
const unchanged = JSON.stringify(seed);
let store = records.assign(seed, 'deal', 'deal1', 'WOS-FL-0100');
assert.strictEqual(store.reviewed_deals[0].record_ref, 'WOS-FL-0100');
store = { ...store, reviewed_deals: store.reviewed_deals.concat({ id: 'deal2', state: 'FL' }) };
store = records.assign(store, 'deal', 'deal2'); assert.strictEqual(store.reviewed_deals[1].record_ref, 'WOS-FL-0101');
assert.strictEqual(records.assign(store, 'deal', 'deal1'), store);
assert.throws(() => records.assign(store, 'deal', 'deal2', 'WOS-FL-0102'), /ref_conflict/);
assert.throws(() => records.assign(store, 'buyer', 'buyer1', 'WOS-FL-0100'), /kind_mismatch/);
assert.throws(() => records.assign(store, 'deal', 'deal2', 'WOS-TX-0001'), /ref_conflict/);
const correctedState={...store,reviewed_deals:store.reviewed_deals.map(r=>r.id==='deal1'?{...r,state:'TX'}:r)};
assert.strictEqual(records.assign(correctedState,'deal','deal1','WOS-FL-0100'),correctedState,'an existing reference is not renamed when source facts are corrected');
assert.throws(() => records.ref('BUY-12345'), /ref_invalid/);
const duplicate = { ...store, buyers: [{ id: 'buyer1', record_ref: 'BUY-0001' }, { id: 'buyer2' }] };
assert.throws(() => records.assign(duplicate, 'buyer', 'buyer2', 'BUY-0001'), /ref_conflict/);
const exhausted = { ...seed, record_reference_sequences: { BUY: 9999 } };
assert.throws(() => records.assign(exhausted, 'buyer', 'buyer1'), /ref_exhausted/);
store = records.assignMissing(store, context).store;
assert.strictEqual(store.leads[0].reference_id, 'LEGACY-1');
assert.strictEqual(store.leads[0].record_ref, 'WOS-FL-0102'); assert.strictEqual(store.buyers[0].record_ref, 'BUY-0001');
assert.deepStrictEqual(store.activities[0], seed.activities[0]);
assert.ok(records.listActivity(store,{reference:'WOS-FL-0102'}).items.some(a=>a.summary==='Historical note'),'canonical ref resolves legacy lead history without rewriting it');
const before = JSON.stringify(store.activities);
store = records.recordEvent(store, 'deal', 'deal1', 'status_change', 'Stage recorded by operator.', context);
assert.strictEqual(JSON.stringify(store.activities.slice(0, -1)), before);
assert.strictEqual(store.activities.at(-1).deal_ref, 'WOS-FL-0100');
store = records.registerMatch(store, 'deal1', 'buyer1', context);
assert.strictEqual(records.matchReference(store, 'deal1', 'buyer1'), 'M-0001');
assert.strictEqual(records.registerMatch(store, 'deal1', 'buyer1', context), store);
const interaction = records.validateInteraction({ kind: 'interaction', ts: '2026-10-07T12:00:00Z', who: 'Assistant', channel: 'email', dir: 'out', with: 'private-contact@example.test', ref: 'BUY-0001', summary: 'Reported draft; sending is not established.', body: 'private message body' }, now);
const imported = records.importInteraction(store, interaction, context); store = imported.store;
assert.strictEqual(store.activities.at(-1).type, 'interaction_reported', 'direction never infers that a message was sent');
assert.strictEqual(store.activities.at(-1).buyer_id, 'buyer1');
assert.strictEqual(records.importInteraction(store, interaction, context).results[0].result, 'duplicate');
assert.throws(() => records.importInteraction(store, { ...interaction, ref: 'BUY-9999' }, context), /ref_unknown/);
assert.throws(() => records.validateInteraction({ ...interaction, ts: '2026-11-31T12:00:00Z' }, now), /date_invalid/);
assert.throws(() => records.validateInteraction({ ...interaction, ts: '2027-01-01T12:00:00Z' }, now), /date_invalid/);
assert.throws(() => records.validateInteraction({ ...interaction, approval: 'approved' }, now), /interaction_invalid/);
const view = records.listActivity(store, { reference: 'BUY-0001' });
assert.ok(view.items.some(a => a.attribution === 'imported_report'));
assert.ok(!JSON.stringify(view).includes('private-contact@example.test')); assert.ok(!JSON.stringify(view).includes('private message body'));
assert.ok(records.search(store, 'WOS-FL-0100').some(r => r.id === 'deal1'));
assert.strictEqual(JSON.stringify(seed), unchanged);
const legacyNamespace={leads:[{id:'older',state:'FL',reference_id:'WOS-FL-0500'},{id:'newer',state:'FL'}]};
const migratedNamespace=records.assignMissing(legacyNamespace,context).store;
assert.strictEqual(migratedNamespace.leads[0].record_ref,'WOS-FL-0500');assert.strictEqual(migratedNamespace.leads[1].record_ref,'WOS-FL-0501');
const large = { leads:Array.from({length:12039},(_,i)=>({id:'fixture-'+i,state:i<6000?'FL':'TX'})),activities:[] };
const assignedLarge=records.assignMissing(large,context);assert.strictEqual(assignedLarge.count,12039);
assert.strictEqual(new Set(assignedLarge.store.leads.map(r=>r.record_ref)).size,12039);
assert.ok(large.leads.every(r=>!r.record_ref),'large assignment does not mutate its input');
const tooMany={leads:Array.from({length:10000},(_,i)=>({id:'capacity-'+i,state:'FL'}))};
assert.throws(()=>records.assignMissing(tooMany,context),/ref_exhausted/);assert.ok(tooMany.leads.every(r=>!r.record_ref));
const saved = [global.fetch, Date.now, fs.writeFileSync]; let effects = 0;
try { const deny = () => { effects++; throw Error('side effect'); }; global.fetch = deny; Date.now = deny; fs.writeFileSync = deny; records.listActivity(store); records.search(store, 'BUY'); records.assignMissing(seed, context); } finally { [global.fetch, Date.now, fs.writeFileSync] = saved; }
assert.strictEqual(effects, 0);
console.log('Record metadata: stable references, conflicts/exhaustion, immutable history, reported interactions, redacted read model and purity passed.');
